// This file was generated by counterfeiter
package commandsfakes

import (
	"sync"

	clocker "github.com/mdelillo/claimer/locker"
)

type FakeLocker struct {
	ClaimLockStub        func(pool, username, message string) error
	claimLockMutex       sync.RWMutex
	claimLockArgsForCall []struct {
		pool     string
		username string
		message  string
	}
	claimLockReturns struct {
		result1 error
	}
	claimLockReturnsOnCall map[int]struct {
		result1 error
	}
	CreatePoolStub        func(pool, username string) error
	createPoolMutex       sync.RWMutex
	createPoolArgsForCall []struct {
		pool     string
		username string
	}
	createPoolReturns struct {
		result1 error
	}
	createPoolReturnsOnCall map[int]struct {
		result1 error
	}
	DestroyPoolStub        func(pool, username string) error
	destroyPoolMutex       sync.RWMutex
	destroyPoolArgsForCall []struct {
		pool     string
		username string
	}
	destroyPoolReturns struct {
		result1 error
	}
	destroyPoolReturnsOnCall map[int]struct {
		result1 error
	}
	ReleaseLockStub        func(pool, username string) error
	releaseLockMutex       sync.RWMutex
	releaseLockArgsForCall []struct {
		pool     string
		username string
	}
	releaseLockReturns struct {
		result1 error
	}
	releaseLockReturnsOnCall map[int]struct {
		result1 error
	}
	StatusStub        func() (locks []clocker.Lock, err error)
	statusMutex       sync.RWMutex
	statusArgsForCall []struct{}
	statusReturns     struct {
		result1 []clocker.Lock
		result2 error
	}
	statusReturnsOnCall map[int]struct {
		result1 []clocker.Lock
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeLocker) ClaimLock(pool string, username string, message string) error {
	fake.claimLockMutex.Lock()
	ret, specificReturn := fake.claimLockReturnsOnCall[len(fake.claimLockArgsForCall)]
	fake.claimLockArgsForCall = append(fake.claimLockArgsForCall, struct {
		pool     string
		username string
		message  string
	}{pool, username, message})
	fake.recordInvocation("ClaimLock", []interface{}{pool, username, message})
	fake.claimLockMutex.Unlock()
	if fake.ClaimLockStub != nil {
		return fake.ClaimLockStub(pool, username, message)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.claimLockReturns.result1
}

func (fake *FakeLocker) ClaimLockCallCount() int {
	fake.claimLockMutex.RLock()
	defer fake.claimLockMutex.RUnlock()
	return len(fake.claimLockArgsForCall)
}

func (fake *FakeLocker) ClaimLockArgsForCall(i int) (string, string, string) {
	fake.claimLockMutex.RLock()
	defer fake.claimLockMutex.RUnlock()
	return fake.claimLockArgsForCall[i].pool, fake.claimLockArgsForCall[i].username, fake.claimLockArgsForCall[i].message
}

func (fake *FakeLocker) ClaimLockReturns(result1 error) {
	fake.ClaimLockStub = nil
	fake.claimLockReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeLocker) ClaimLockReturnsOnCall(i int, result1 error) {
	fake.ClaimLockStub = nil
	if fake.claimLockReturnsOnCall == nil {
		fake.claimLockReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.claimLockReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeLocker) CreatePool(pool string, username string) error {
	fake.createPoolMutex.Lock()
	ret, specificReturn := fake.createPoolReturnsOnCall[len(fake.createPoolArgsForCall)]
	fake.createPoolArgsForCall = append(fake.createPoolArgsForCall, struct {
		pool     string
		username string
	}{pool, username})
	fake.recordInvocation("CreatePool", []interface{}{pool, username})
	fake.createPoolMutex.Unlock()
	if fake.CreatePoolStub != nil {
		return fake.CreatePoolStub(pool, username)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.createPoolReturns.result1
}

func (fake *FakeLocker) CreatePoolCallCount() int {
	fake.createPoolMutex.RLock()
	defer fake.createPoolMutex.RUnlock()
	return len(fake.createPoolArgsForCall)
}

func (fake *FakeLocker) CreatePoolArgsForCall(i int) (string, string) {
	fake.createPoolMutex.RLock()
	defer fake.createPoolMutex.RUnlock()
	return fake.createPoolArgsForCall[i].pool, fake.createPoolArgsForCall[i].username
}

func (fake *FakeLocker) CreatePoolReturns(result1 error) {
	fake.CreatePoolStub = nil
	fake.createPoolReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeLocker) CreatePoolReturnsOnCall(i int, result1 error) {
	fake.CreatePoolStub = nil
	if fake.createPoolReturnsOnCall == nil {
		fake.createPoolReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createPoolReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeLocker) DestroyPool(pool string, username string) error {
	fake.destroyPoolMutex.Lock()
	ret, specificReturn := fake.destroyPoolReturnsOnCall[len(fake.destroyPoolArgsForCall)]
	fake.destroyPoolArgsForCall = append(fake.destroyPoolArgsForCall, struct {
		pool     string
		username string
	}{pool, username})
	fake.recordInvocation("DestroyPool", []interface{}{pool, username})
	fake.destroyPoolMutex.Unlock()
	if fake.DestroyPoolStub != nil {
		return fake.DestroyPoolStub(pool, username)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.destroyPoolReturns.result1
}

func (fake *FakeLocker) DestroyPoolCallCount() int {
	fake.destroyPoolMutex.RLock()
	defer fake.destroyPoolMutex.RUnlock()
	return len(fake.destroyPoolArgsForCall)
}

func (fake *FakeLocker) DestroyPoolArgsForCall(i int) (string, string) {
	fake.destroyPoolMutex.RLock()
	defer fake.destroyPoolMutex.RUnlock()
	return fake.destroyPoolArgsForCall[i].pool, fake.destroyPoolArgsForCall[i].username
}

func (fake *FakeLocker) DestroyPoolReturns(result1 error) {
	fake.DestroyPoolStub = nil
	fake.destroyPoolReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeLocker) DestroyPoolReturnsOnCall(i int, result1 error) {
	fake.DestroyPoolStub = nil
	if fake.destroyPoolReturnsOnCall == nil {
		fake.destroyPoolReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.destroyPoolReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeLocker) ReleaseLock(pool string, username string) error {
	fake.releaseLockMutex.Lock()
	ret, specificReturn := fake.releaseLockReturnsOnCall[len(fake.releaseLockArgsForCall)]
	fake.releaseLockArgsForCall = append(fake.releaseLockArgsForCall, struct {
		pool     string
		username string
	}{pool, username})
	fake.recordInvocation("ReleaseLock", []interface{}{pool, username})
	fake.releaseLockMutex.Unlock()
	if fake.ReleaseLockStub != nil {
		return fake.ReleaseLockStub(pool, username)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.releaseLockReturns.result1
}

func (fake *FakeLocker) ReleaseLockCallCount() int {
	fake.releaseLockMutex.RLock()
	defer fake.releaseLockMutex.RUnlock()
	return len(fake.releaseLockArgsForCall)
}

func (fake *FakeLocker) ReleaseLockArgsForCall(i int) (string, string) {
	fake.releaseLockMutex.RLock()
	defer fake.releaseLockMutex.RUnlock()
	return fake.releaseLockArgsForCall[i].pool, fake.releaseLockArgsForCall[i].username
}

func (fake *FakeLocker) ReleaseLockReturns(result1 error) {
	fake.ReleaseLockStub = nil
	fake.releaseLockReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeLocker) ReleaseLockReturnsOnCall(i int, result1 error) {
	fake.ReleaseLockStub = nil
	if fake.releaseLockReturnsOnCall == nil {
		fake.releaseLockReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.releaseLockReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeLocker) Status() (locks []clocker.Lock, err error) {
	fake.statusMutex.Lock()
	ret, specificReturn := fake.statusReturnsOnCall[len(fake.statusArgsForCall)]
	fake.statusArgsForCall = append(fake.statusArgsForCall, struct{}{})
	fake.recordInvocation("Status", []interface{}{})
	fake.statusMutex.Unlock()
	if fake.StatusStub != nil {
		return fake.StatusStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.statusReturns.result1, fake.statusReturns.result2
}

func (fake *FakeLocker) StatusCallCount() int {
	fake.statusMutex.RLock()
	defer fake.statusMutex.RUnlock()
	return len(fake.statusArgsForCall)
}

func (fake *FakeLocker) StatusReturns(result1 []clocker.Lock, result2 error) {
	fake.StatusStub = nil
	fake.statusReturns = struct {
		result1 []clocker.Lock
		result2 error
	}{result1, result2}
}

func (fake *FakeLocker) StatusReturnsOnCall(i int, result1 []clocker.Lock, result2 error) {
	fake.StatusStub = nil
	if fake.statusReturnsOnCall == nil {
		fake.statusReturnsOnCall = make(map[int]struct {
			result1 []clocker.Lock
			result2 error
		})
	}
	fake.statusReturnsOnCall[i] = struct {
		result1 []clocker.Lock
		result2 error
	}{result1, result2}
}

func (fake *FakeLocker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.claimLockMutex.RLock()
	defer fake.claimLockMutex.RUnlock()
	fake.createPoolMutex.RLock()
	defer fake.createPoolMutex.RUnlock()
	fake.destroyPoolMutex.RLock()
	defer fake.destroyPoolMutex.RUnlock()
	fake.releaseLockMutex.RLock()
	defer fake.releaseLockMutex.RUnlock()
	fake.statusMutex.RLock()
	defer fake.statusMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeLocker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
